FROM ghcr.io/puppeteer/puppeteer:latest

ENV TZ America/Los_Angeles
ENV IMAGE_URL http://client

USER root
RUN apt-get update && apt-get install -y fonts-noto-color-emoji
USER pptruser
COPY ./screenshot.js .

CMD ['node', 'screenshot.js']
