# Build static site
FROM node:20.18.0-slim as base

WORKDIR /app
RUN npm install -g pnpm

FROM base AS build

COPY package.json pnpm-lock.yaml *.config.js index.html ./
COPY src src
COPY public public

RUN pnpm install --frozen-lockfile
RUN pnpm build

# Serve static site from nginx
FROM nginx:stable-alpine

ENV TZ=America/Los_Angeles
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
