FROM ghcr.io/puppeteer/puppeteer:latest

USER root
RUN apt-get update && apt-get install -y cron
USER pptruser

WORKDIR /script
ADD screenshot-cron /etc/cronjob
COPY screenshot.js ./
RUN crontab /etc/cronjob
RUN node screenshot.js
CMD ["cron", "-f"]
