FROM ghcr.io/puppeteer/puppeteer:latest

RUN apt-get update && apt-get install -y cron

WORKDIR /script
ADD screenshot-cron /etc/cronjob
COPY screenshot.js ./
RUN crontab /etc/cronjob
RUN node screenshot.js
CMD ["cron", "-f"]
